/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controladores.ControlaAluno;
import EstruturaDeDados.ListaLigada;
import Objecto.Aluno;
import static GUI.Operacoes.CriarAluno.gravarDados;
import Tabela.TableModelAlunos;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.UUID;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author toshiba
 */
public class PaginaInicial extends javax.swing.JFrame {
    
    ListaLigada listaLigadaAluno = new ListaLigada();
    Aluno a = new Aluno();
    /**
     * Creates new form PaginaInicial
     */
    public PaginaInicial() {
        initComponents();
        myInitComp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPrincipalPane = new javax.swing.JTabbedPane();
        pnCadastro = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txID = new javax.swing.JTextField();
        txNome = new javax.swing.JTextField();
        txApelido = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rbMasculino = new javax.swing.JRadioButton();
        rbFemenino = new javax.swing.JRadioButton();
        cbNacionalidades = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btLimpar = new javax.swing.JButton();
        btGravar = new javax.swing.JButton();
        pnEliminar = new javax.swing.JPanel();
        pnListagem = new javax.swing.JPanel();
        dialogOne = new javax.swing.JOptionPane();
        pnAlteraDados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDados = new javax.swing.JTable();
        btGravarDadosTabela = new javax.swing.JButton();
        pnBuscar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGA - MAIN PAGE");
        setBackground(new java.awt.Color(51, 51, 51));
        setResizable(false);

        pnPrincipalPane.setBackground(new java.awt.Color(51, 51, 51));
        pnPrincipalPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnPrincipalPane.setForeground(new java.awt.Color(0, 204, 51));
        pnPrincipalPane.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N

        pnCadastro.setBackground(new java.awt.Color(51, 51, 51));
        pnCadastro.setForeground(new java.awt.Color(0, 204, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(0, 204, 51));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE ALUNOS");

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID do Aluno: ");

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NOME: ");

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("APELIDO:");

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SEXO:");

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("NACIONALIDADE:");

        txID.setEditable(false);
        txID.setBackground(new java.awt.Color(51, 51, 51));
        txID.setForeground(new java.awt.Color(0, 204, 51));
        txID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIDActionPerformed(evt);
            }
        });

        txNome.setBackground(new java.awt.Color(51, 51, 51));
        txNome.setForeground(new java.awt.Color(0, 204, 51));

        txApelido.setBackground(new java.awt.Color(51, 51, 51));
        txApelido.setForeground(new java.awt.Color(0, 204, 51));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(0, 204, 51));

        rbMasculino.setBackground(new java.awt.Color(51, 51, 51));
        rbMasculino.setForeground(new java.awt.Color(0, 204, 51));
        rbMasculino.setText("MASCULINO");

        rbFemenino.setBackground(new java.awt.Color(51, 51, 51));
        rbFemenino.setForeground(new java.awt.Color(0, 204, 51));
        rbFemenino.setText("FEMENINO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbMasculino)
                    .addComponent(rbFemenino))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbMasculino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(rbFemenino))
        );

        cbNacionalidades.setBackground(new java.awt.Color(0, 204, 51));
        cbNacionalidades.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        cbNacionalidades.setForeground(new java.awt.Color(51, 51, 51));
        cbNacionalidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[ESCOLHA UMA OPCAO]", "1.MOCAMBICANA", "2.RUSSA", "3.INGLESA", "4.HEBRAICA", "5.SUL-AFRICANA" }));
        cbNacionalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNacionalidadesActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setForeground(new java.awt.Color(0, 204, 51));

        btLimpar.setBackground(new java.awt.Color(51, 51, 51));
        btLimpar.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btLimpar.setForeground(new java.awt.Color(0, 204, 51));
        btLimpar.setText("LIMPAR ");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btGravar.setBackground(new java.awt.Color(51, 51, 51));
        btGravar.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btGravar.setForeground(new java.awt.Color(0, 204, 51));
        btGravar.setText("GRAVAR");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txApelido)
                            .addComponent(txNome, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(txID))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbNacionalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbNacionalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout pnCadastroLayout = new javax.swing.GroupLayout(pnCadastro);
        pnCadastro.setLayout(pnCadastroLayout);
        pnCadastroLayout.setHorizontalGroup(
            pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnCadastroLayout.setVerticalGroup(
            pnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnPrincipalPane.addTab("CADASTRAR ALUNO", pnCadastro);

        pnEliminar.setBackground(new java.awt.Color(51, 51, 51));
        pnEliminar.setForeground(new java.awt.Color(0, 204, 51));

        javax.swing.GroupLayout pnEliminarLayout = new javax.swing.GroupLayout(pnEliminar);
        pnEliminar.setLayout(pnEliminarLayout);
        pnEliminarLayout.setHorizontalGroup(
            pnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );
        pnEliminarLayout.setVerticalGroup(
            pnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        pnPrincipalPane.addTab("ELIMINAR ALUNO", pnEliminar);

        pnListagem.setBackground(new java.awt.Color(51, 51, 51));
        pnListagem.setForeground(new java.awt.Color(0, 204, 51));

        javax.swing.GroupLayout pnListagemLayout = new javax.swing.GroupLayout(pnListagem);
        pnListagem.setLayout(pnListagemLayout);
        pnListagemLayout.setHorizontalGroup(
            pnListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dialogOne, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(506, Short.MAX_VALUE))
        );
        pnListagemLayout.setVerticalGroup(
            pnListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dialogOne, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        dialogOne.showInputDialog(null,"1 - Todos alunos" + "\n" +"2 - Mesmo nome"+"\n"+"3 - Ordem alfabetica");

        pnPrincipalPane.addTab("LISTAR ALUNOS", pnListagem);

        pnAlteraDados.setBackground(new java.awt.Color(51, 51, 51));
        pnAlteraDados.setForeground(new java.awt.Color(0, 204, 51));

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setForeground(new java.awt.Color(0, 204, 51));

        tabelaDados.setBackground(new java.awt.Color(51, 51, 51));
        tabelaDados.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        tabelaDados.setForeground(new java.awt.Color(0, 204, 51));
        tabelaDados.setAutoscrolls(false);
        tabelaDados.setColumnSelectionAllowed(true);
        tabelaDados.setGridColor(new java.awt.Color(0, 204, 51));
        tabelaDados.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(tabelaDados);
        tabelaDados.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btGravarDadosTabela.setBackground(new java.awt.Color(51, 51, 51));
        btGravarDadosTabela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btGravarDadosTabela.setForeground(new java.awt.Color(0, 204, 51));
        btGravarDadosTabela.setText("Gravar");

        javax.swing.GroupLayout pnAlteraDadosLayout = new javax.swing.GroupLayout(pnAlteraDados);
        pnAlteraDados.setLayout(pnAlteraDadosLayout);
        pnAlteraDadosLayout.setHorizontalGroup(
            pnAlteraDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAlteraDadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btGravarDadosTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(292, 292, 292))
        );
        pnAlteraDadosLayout.setVerticalGroup(
            pnAlteraDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAlteraDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btGravarDadosTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnPrincipalPane.addTab("ALTERAR DADOS DE ALUNOS", pnAlteraDados);

        pnBuscar.setBackground(new java.awt.Color(51, 51, 51));
        pnBuscar.setForeground(new java.awt.Color(0, 204, 51));

        javax.swing.GroupLayout pnBuscarLayout = new javax.swing.GroupLayout(pnBuscar);
        pnBuscar.setLayout(pnBuscarLayout);
        pnBuscarLayout.setHorizontalGroup(
            pnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );
        pnBuscarLayout.setVerticalGroup(
            pnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        pnPrincipalPane.addTab("BUSCAR DADOS DE ALUNO", pnBuscar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipalPane, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipalPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txIDActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        this.txApelido.setText("");
        this.txNome.setText(" ");
        this.txID.setText(a.getId().toString());
        
    }//GEN-LAST:event_btLimparActionPerformed

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == btGravar)
        {
            if(txNome.getText().equals("")||txApelido.getText().equals("")
                    ||cbNacionalidades.getItemAt(0).equals("[ESCOLHA UMA OPCAO]")||!btgCenas.getSelection().isSelected())
            {
               JOptionPane.showMessageDialog(null, "Todos campos devem ser preenchidos. ");

            }else{
                var Id = UUID.fromString(txID.getText());
                
                a.setNome(txNome.getText());
                a.setApelido(txApelido.getText());
                a.setNacionalidade(cbNacionalidades.getSelectedItem().toString());
                a.setSexo(btgCenas.getSelection().toString());
                a.setId(Id);
                
                ControlaAluno ca = new ControlaAluno();
                ca.criarAluno(listaLigadaAluno, a);

                btLimpar.doClick();
                txID.setText(a.getId().toString());
            }
        }  
    }//GEN-LAST:event_btGravarActionPerformed

    private void cbNacionalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNacionalidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNacionalidadesActionPerformed

    public  void gravarDados(){
	FileOutputStream fos = null;
	ObjectOutputStream oos = null;
	try{
			
            fos = new FileOutputStream("alunos.dat");
            oos = new ObjectOutputStream(fos);
			
            oos.writeObject(listaLigadaAluno);
            oos.flush();
            oos.close();
			
	}catch(IOException e){
            e.getMessage();
	}
    }
    
    private  ListaLigada lerDados() {
	FileInputStream fis = null;
	ObjectInputStream ois = null;
	try {
            fis = new FileInputStream("alunos.dat");
            ois = new ObjectInputStream(fis);
            listaLigadaAluno =(ListaLigada) ois.readObject();
            ois.close();
            fis.close();
	} catch (IOException | ClassNotFoundException je) {
            je.printStackTrace();
        }
	return listaLigadaAluno ;
    }  
    
    private void myInitComp(){
        tableModel = new TableModelAlunos();
        this.tabelaDados.setModel(tableModel);
        txID.setText(String.valueOf(a.getId()));
        this.btgCenas = new ButtonGroup();
        this.btgCenas.add(rbMasculino);
        this.btgCenas.add(rbFemenino);
    }
    
    private ButtonGroup btgCenas;
    private TableModelAlunos tableModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btGravarDadosTabela;
    private javax.swing.JButton btLimpar;
    private javax.swing.JComboBox<String> cbNacionalidades;
    private javax.swing.JOptionPane dialogOne;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnAlteraDados;
    private javax.swing.JPanel pnBuscar;
    private javax.swing.JPanel pnCadastro;
    private javax.swing.JPanel pnEliminar;
    private javax.swing.JPanel pnListagem;
    private javax.swing.JTabbedPane pnPrincipalPane;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTable tabelaDados;
    private javax.swing.JTextField txApelido;
    private javax.swing.JTextField txID;
    private javax.swing.JTextField txNome;
    // End of variables declaration//GEN-END:variables
}
