
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Operacoes;


import EstruturaDeDados.ListaLigada;
import Objecto.Aluno;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Khalidy Safar
 */
public class CriarAluno extends JFrame{
    Aluno al = new Aluno();
    static ListaLigada listaLigadaAlunos = new ListaLigada ();
    
    public CriarAluno (){
        initComponents();
        this.txID.setText(String.valueOf(al.getId()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbID = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbApelido = new javax.swing.JLabel();
        lbDataNascimento = new javax.swing.JLabel();
        lbNacionanlidade = new javax.swing.JLabel();
        cbNacionalidades = new javax.swing.JComboBox<>();
        txDataNascimento = new javax.swing.JTextField();
        txID = new javax.swing.JTextField();
        txNome = new javax.swing.JTextField();
        txApelido = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btGravar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE ALUNOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setForeground(new java.awt.Color(0, 204, 51));

        lbID.setBackground(new java.awt.Color(51, 51, 51));
        lbID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbID.setForeground(new java.awt.Color(0, 204, 51));
        lbID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbID.setText("ID:");

        lbNome.setBackground(new java.awt.Color(51, 51, 51));
        lbNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNome.setForeground(new java.awt.Color(0, 204, 51));
        lbNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNome.setText("NOME:");

        lbApelido.setBackground(new java.awt.Color(51, 51, 51));
        lbApelido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbApelido.setForeground(new java.awt.Color(0, 204, 51));
        lbApelido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbApelido.setText("APELIDO:");

        lbDataNascimento.setBackground(new java.awt.Color(51, 51, 51));
        lbDataNascimento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDataNascimento.setForeground(new java.awt.Color(0, 204, 51));
        lbDataNascimento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDataNascimento.setText("DATA DE NASCIMENTO:");

        lbNacionanlidade.setBackground(new java.awt.Color(51, 51, 51));
        lbNacionanlidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNacionanlidade.setForeground(new java.awt.Color(0, 204, 51));
        lbNacionanlidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNacionanlidade.setText("NACIONALIDADE:");

        cbNacionalidades.setBackground(new java.awt.Color(51, 51, 51));
        cbNacionalidades.setForeground(new java.awt.Color(0, 204, 51));
        cbNacionalidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Escolha uma opção]", "Moçambicana", "Russa", "Israelita", "Americana" }));

        txDataNascimento.setBackground(new java.awt.Color(51, 51, 51));
        txDataNascimento.setForeground(new java.awt.Color(0, 204, 51));
        txDataNascimento.setSelectedTextColor(new java.awt.Color(0, 204, 51));

        txID.setEditable(false);
        txID.setBackground(new java.awt.Color(51, 51, 51));
        txID.setForeground(new java.awt.Color(0, 204, 51));
        txID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txID.setSelectedTextColor(new java.awt.Color(0, 204, 51));

        txNome.setBackground(new java.awt.Color(51, 51, 51));
        txNome.setForeground(new java.awt.Color(0, 204, 51));
        txNome.setSelectedTextColor(new java.awt.Color(0, 204, 51));

        txApelido.setBackground(new java.awt.Color(51, 51, 51));
        txApelido.setForeground(new java.awt.Color(0, 204, 51));
        txApelido.setSelectedTextColor(new java.awt.Color(0, 204, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbID, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbApelido)
                                .addGap(28, 28, 28)
                                .addComponent(txApelido, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbDataNascimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txDataNascimento))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbNacionanlidade)
                                .addGap(18, 18, 18)
                                .addComponent(cbNacionalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(107, 107, 107))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbID)
                    .addComponent(lbDataNascimento)
                    .addComponent(txDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbApelido)
                            .addComponent(txApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNacionanlidade)
                            .addComponent(cbNacionalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        btGravar.setBackground(new java.awt.Color(51, 51, 51));
        btGravar.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btGravar.setForeground(new java.awt.Color(0, 204, 51));
        btGravar.setText("GRAVAR");
        btGravar.setToolTipText("");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        btLimpar.setBackground(new java.awt.Color(51, 51, 51));
        btLimpar.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btLimpar.setForeground(new java.awt.Color(0, 204, 51));
        btLimpar.setText("LIMPAR");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setBackground(new java.awt.Color(51, 51, 51));
        btSair.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btSair.setForeground(new java.awt.Color(0, 204, 51));
        btSair.setText("SAIR");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(btGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btGravar, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    public static void gravarDados(){
	FileOutputStream fos=null;
	ObjectOutputStream oos=null;
	try{
			
            fos = new FileOutputStream("alunos.txt");
            oos = new ObjectOutputStream(fos);
			
            oos.writeObject(listaLigadaAlunos);
            oos.flush();
            oos.close();
			
	}catch(IOException e){
            e.getMessage();
	}
    }
    
    private static ListaLigada lerDados() {
	FileInputStream fis=null;
	ObjectInputStream ois=null;
	try {
            fis = new FileInputStream("alunos.txt");
            ois = new ObjectInputStream(fis);
            listaLigadaAlunos =(ListaLigada) ois.readObject();
            ois.close();
            fis.close();
	} catch (IOException | ClassNotFoundException je) {
            je.printStackTrace();
        }
	return listaLigadaAlunos;
    }                                       
    
    private void btGravarActionPerformed(java.awt.event.ActionEvent evt){                                         
        // TODO add your handling code here:
       // try{
            
            //SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            //Date formato = df.parse(this.txDataNascimento.toString());
        
            listaLigadaAlunos = lerDados();
            int contador;
				
            if(txNome.getText().length() > 0 && txApelido.getText().length() > 0 && txDataNascimento.getText().length() > 0 && txID.getText().length() > 0) {
                try {
                    Aluno a = new Aluno();
					
                    if(listaLigadaAlunos.tamanho() >= 100) {
                        JOptionPane.showMessageDialog(null," Atingiu o limite de clientes ");
                    }
                    else {
                        do {
                            contador = 0;
                            a.setId(a.getId());
                            for (int i = 0; i < listaLigadaAlunos.tamanho(); i++) {
                                if (a.getId() == ((Aluno) listaLigadaAlunos.pega(i)).getId()) {
                                    contador++;
                                }
                            }
                            if (contador == 0) {
                                txID.setText(String.valueOf(a.getId()));
                                a.setNome(txNome.getText());
                                a.setApelido(txApelido.getText());
                                a.setNacionalidade(cbNacionalidades.getSelectedItem().toString());
                                //a.setDataNascimento(formato);

                                listaLigadaAlunos.adicionaFim(a);
                                gravarDados();
                                JOptionPane.showMessageDialog(null,"Aluno cadastrado com sucesso! ");
                                btLimpar.doClick();
                            } 
                        } while (contador !=0);
                    }
                }catch (Exception e1) {
                    JOptionPane.showMessageDialog(null, "Inseriu valor invalido num dos campos.");
                    e1.printStackTrace();
                }
            }else {
                JOptionPane.showMessageDialog(null, "Algum campo não está preenchido correctamente.");
            }
            
        //}catch(Exception ex){
          //  JOptionPane.showMessageDialog(this, ex.getMessage());
        
       // }

    }                                        

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        this.txApelido.setText("");
        this.txDataNascimento.setText("");
        this.txID.setText("");
        this.txNome.setText("");
    }                                        

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        System.exit(DISPOSE_ON_CLOSE);
    }                                      

    // Variables declaration - do not modify                     
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<String> cbNacionalidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbApelido;
    private javax.swing.JLabel lbDataNascimento;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbNacionanlidade;
    private javax.swing.JLabel lbNome;
    private javax.swing.JTextField txApelido;
    private javax.swing.JTextField txDataNascimento;
    private javax.swing.JTextField txID;
    private javax.swing.JTextField txNome;
    // End of variables declaration         
}